### ISSUE TITLE
trigger rebuild for nav

### ISSUE THREAD

**Issue by billmcmillin** [DLFMetadataAssessment/EnvironmentalScan#32] opened 2017-10-11 14:09 UTC

**Comment by kateefly** [comment] 2017-10-11 14:32
Fixed with commit 52fdbb4dfb947dd7c0b0a87a8a759dc30b8435e0. Everything seems to be working as intended (except for header numbering, which is a known issue)

**Closed by kateefly** 2017-10-11 14:32 UTC
